DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS sample;
DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS lab;

CREATE TABLE lab (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  initials TEXT NOT NULL,
  lab_id INTEGER NOT NULL,
  FOREIGN KEY (lab_id) REFERENCES lab (id)
);



CREATE TABLE sample (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lab_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  date TIMESTAMP NOT NULL,
  comment TEXT,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (lab_id) REFERENCES lab (id)

);

CREATE TABLE note (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  sample_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (sample_id) REFERENCES sample (id)
);